# -*- coding: utf-8 -*-
"""Playground.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFnn9OBSVehnAQTQRSYmByITn_wIcj1G
"""

import streamlit as st

st.title("Hello Streamlit-er 👋")
st.markdown(
    """
    This is a playground for you to try Streamlit and have fun.

    **There's :rainbow[so much] you can build!**

    We prepared a few examples for you to get started. Just
    click on the buttons above and discover what you can do
    with Streamlit.
    """
)

if st.button("Send balloons!"):
    st.balloons()